---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformLint.yml@fix/workflows
    with:
      terraformPath: .
  validate:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformValidate.yml@fix/workflows
    with:
      terraformPath: .
    needs: Lint
  plan:
    strategy:
      matrix:
        environments: [development,pre-production,production]
        whitepapers: [basic-ec2]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformPlan.yml@fix/workflows
    with:
      workspace: ${{ matrix.environments }}
      whitepaper: ${{ matrix.whitepapers }}
    needs: [lint,validate]
